### ISSUE TITLE
How do I change method naming convention?

### ISSUE THREAD

**Issue by murilogibim** [unchase/Unchase.OpenAPI.Connectedservice#1]
I would like to change method naming convention to have less verbose naming, is it possible?

Current behavior:
path: /api/services/app/Account/Register
csharp method: ApiServicesAppAccountRegister

Expected: AppAccountRegister

Thank you!

**Comment by unchase** [comment]
For changing method naming in c# client-code generation you should change **"Operation Generation Mode"** option on *"MultipleClientsFromFirstTagAndOperationId"* in **"Client"** section in **"CSharp Client Settings"** wizard tab.

**Comment by murilogibim** [comment]
I changed it to generate one client per tag and it's pretty much the result I wanted. 

Thank you!!

**Comment by Alfetta159** [comment]
Why can't we just use the operation ID or some other property value of the controller/action attributes (e.g. Http[Verb], SwaggerOperation, ActionName, etc.)?

**Comment by unchase** [comment]
> Why can't we just use the operation ID or some other property value of the controller/action attributes (e.g. Http[Verb], SwaggerOperation, ActionName, etc.)?

This is a good question to ask [here](https://github.com/RicoSuter/NSwag/issues).
