### ISSUE TITLE
The Extension doesn't restore the previous settings for a client update.

### ISSUE THREAD

**Issue by BRB2000** [unchase/Unchase.OpenAPI.Connectedservice#10]
The Extension doesn't restore the previous settings for a client update. I have to re-enter settings like the base class every time. I would also be very nice, if you could just right-click the json file to update the client.

Other than that, it is a real time saver. Thank you so much.

**Comment by unchase** [comment]
Have you tried updating generated code, as in the screenshot?

![update](https://user-images.githubusercontent.com/29679226/68761664-9fa26c80-0625-11ea-9198-1adc783961bf.png)

**Comment by BRB2000** [comment]
How could I miss that?! Thank you very much!

**Comment by unchase** [comment]
You are welcome.

**Comment by BRB2000** [comment]
For some reason ,the extension restores the wrong settings (the one of another solution in the same Azure Dev Ops Project.

**Comment by BRB2000** [comment]
`{
  "ProviderId": "Unchase.OpenAPI.ConnectedService",
  "Version": "1.3.7232.27378",
  "GettingStartedDocument": {
    "Uri": "https://github.com/unchase/Unchase.OpenAPI.Connectedservice/"
  },
  "ExtendedData": {
    "ServiceName": "WebService",
    "Endpoint": "http://localhost:51885/swagger/WebService/swagger.json",
    "GeneratedFileNamePrefix": null,
    "GenerateCSharpClient": true,
    "GenerateTypeScriptClient": false,
    "GenerateCSharpController": false,
    "OpenApiToCSharpClientCommand": {
      "ClientBaseClass": "ClientBase",
      "ConfigurationClass": null,
      "GenerateClientClasses": true,
      "GenerateClientInterfaces": false,
      "InjectHttpClient": true,
      "DisposeHttpClient": true,
      "ProtectedMethods": [],
      "GenerateExceptionClasses": true,
      "ExceptionClass": "ApiException",
      "WrapDtoExceptions": true,
      "UseHttpClientCreationMethod": false,
      "HttpClientType": "System.Net.Http.HttpClient",
      "UseHttpRequestMessageCreationMethod": true,
      "UseBaseUrl": true,
      "GenerateBaseUrlProperty": true,
      "GenerateSyncMethods": false,
      "ExposeJsonSerializerSettings": false,
      "ClientClassAccessModifier": "public",
      "TypeAccessModifier": "public",
      "GenerateContractsOutput": false,
      "ContractsNamespace": null,
      "ContractsOutputFilePath": null,
      "ParameterDateTimeFormat": "s",
      "GenerateUpdateJsonSerializerSettingsMethod": true,
      "SerializeTypeInformation": false,
      "QueryNullValue": "",
      "ClassName": "{controller}Client",
      "OperationGenerationMode": 5,
      "AdditionalNamespaceUsages": [],
      "AdditionalContractNamespaceUsages": [],
      "GenerateOptionalParameters": false,
      "GenerateJsonMethods": false,
      "EnforceFlagEnums": false,
      "ParameterArrayType": "System.Collections.Generic.IEnumerable",
      "ParameterDictionaryType": "System.Collections.Generic.IDictionary",
      "ResponseArrayType": "System.Collections.Generic.ICollection",
      "ResponseDictionaryType": "System.Collections.Generic.IDictionary",
      "WrapResponses": true,
      "WrapResponseMethods": [],
      "GenerateResponseClasses": true,
      "ResponseClass": "SwaggerResponse",
      "Namespace": "WebBackend.WebService",
      "RequiredPropertiesMustBeDefined": true,
      "DateType": "System.DateTimeOffset",
      "JsonConverters": null,
      "AnyType": "object",
      "DateTimeType": "System.DateTimeOffset",
      "TimeType": "System.TimeSpan",
      "TimeSpanType": "System.TimeSpan",
      "ArrayType": "System.Collections.Generic.ICollection",
      "ArrayInstanceType": "System.Collections.ObjectModel.Collection",
      "DictionaryType": "System.Collections.Generic.IDictionary",
      "DictionaryInstanceType": "System.Collections.Generic.Dictionary",
      "ArrayBaseType": "System.Collections.ObjectModel.Collection",
      "DictionaryBaseType": "System.Collections.Generic.Dictionary",
      "ClassStyle": 0,
      "GenerateDefaultValues": true,
      "GenerateDataAnnotations": true,
      "ExcludedTypeNames": [],
      "ExcludedParameterNames": [],
      "HandleReferences": false,
      "GenerateImmutableArrayProperties": false,
      "GenerateImmutableDictionaryProperties": false,
      "JsonSerializerSettingsTransformationMethod": null,
      "InlineNamedArrays": false,
      "InlineNamedDictionaries": false,
      "InlineNamedTuples": true,
      "InlineNamedAny": false,
      "GenerateDtoTypes": true,
      "GenerateOptionalPropertiesAsNullable": false,
      "TemplateDirectory": null,
      "TypeNameGeneratorType": null,
      "PropertyNameGeneratorType": null,
      "EnumNameGeneratorType": null,
      "ServiceHost": null,
      "ServiceSchemes": null,
      "output": "WebServiceClient.Generated.cs"
    },
    "OpenApiToTypeScriptClientCommand": null,
    "OpenApiToCSharpControllerCommand": null,
    "Variables": null,
    "Runtime": 0,
    "CopySpecification": false,
    "OpenGeneratedFilesOnComplete": false,
    "UseNetworkCredentials": false,
    "NetworkCredentialsUserName": null,
    "NetworkCredentialsPassword": null,
    "NetworkCredentialsDomain": null,
    "WebProxyUri": null,
    "UseWebProxy": false,
    "UseWebProxyCredentials": false,
    "WebProxyNetworkCredentialsUserName": null,
    "WebProxyNetworkCredentialsPassword": null,
    "WebProxyNetworkCredentialsDomain": null
  }
}`
This is the ConnectedService.json. When i right-click the folder to update the client, the following settings are loaded:
![image](https://user-images.githubusercontent.com/16980650/68849600-a804b100-06d2-11ea-8b06-053d8d2a83d9.png)
