### ISSUE TITLE
Route Template

### ISSUE THREAD

**Issue by BolatovAlau** [unchase/Unchase.OpenAPI.Connectedservice#11]
is here a way to template a routing
example
api/**_blahblah_**/{controller}/**_blahblah_**/{action}

**Comment by unchase** [comment]
Не совсем понял в чём вопрос. Можно на русском.

**Comment by BolatovAlau** [comment]
можно ли задать шаблон для роутинга

например указать в каком место будет стоять то или иное значение

api/{controller}/CustomProject/{method}

если контроллен будет UsersController 
и метод будет GetRoles

то тогда по этому шаблону должен создаться следующий роутинг

api/Users/CustomProject/GetRoles

**Comment by unchase** [comment]
Как я понимаю, вопрос относится к генерации классов контроллеров для C#?
Подключенная служба использует для генерации [NSwag](https://github.com/RicoSuter/NSwag). Все опции для генерации аналогичны [NSwagStudio](https://github.com/RicoSuter/NSwag/wiki/NSwagStudio).
Попробуйте найти ответ в документации к нему. Или заведите [issue](https://github.com/RicoSuter/NSwag/issues/new) там.
