### ISSUE TITLE
Could not find file specified

### ISSUE THREAD

**Issue by tonyoddspherecom** [unchase/Unchase.OpenAPI.Connectedservice#12]
Fresh install into a fairly well seasoned copy of Community Edition 2017, opened a new project, "add..", "Connected service", left everything as default, added service name and URL, hit next, and got standard .net error for newtonsoft being missing.

------------------------------------
Connected services

Cannot Access
"HTTPS://{{MY URL - REMOVED}}".  Could not load file or assembly 'NewtonSoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4ge6b2a6aeed' or one of its dependencies.  The system cannot find the file specified
---------------------------------------------

**Comment by unchase** [comment]
Hi, @tonyoddspherecom 
Could you provide a screenshot and the metadata file?

**Comment by molinch** [comment]
Same issue here, in this case I was loading a local file and trying to generate controller.
See the popup text:
```
---------------------------
Microsoft Visual Studio
---------------------------
Connected Services

Cannot access "****". Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
---------------------------
OK   
---------------------------
```
