### ISSUE TITLE
Compilation error generating C# client. Not all code paths return a value.

### ISSUE THREAD

**Issue by joost00719** [unchase/Unchase.OpenAPI.Connectedservice#13]
An invalid method has been generated.
The method has a code path which does not return anything.
As far as I can see it seems to only affect methods which have a return type of `System.Collections.Generic.ICollection<long>` in my project. Other simular methods return default(sometype), except for the type stated before.

The json used to generate the client can be downloaded from the file attached to this issue.

[swaggerfile.json.txt](https://github.com/unchase/Unchase.OpenAPI.Connectedservice/files/4045506/swaggerfile.json.txt)

**Comment by joost00719** [comment]
Edit: it seems to not only affect ICollection<long>
I think it is a misconfiguration in the api docs, however I still believe the client should return default(sometype) instead of generating compilation errors

**Comment by unchase** [comment]
Since the Сonnected service uses [NSwag Commands](https://www.nuget.org/packages/NSwag.Commands/) for client code generation, you should create the same issue in [this repository](https://github.com/RicoSuter/NSwag/issues).

**Comment by unchase** [comment]
Hi, @joost00719 

Unfortunately, I can’t catch all the bugs that appear in new versions of the library. If you find these bugs, it is best for you to create the issues in the [library repository](https://github.com/RicoSuter/NSwag/issues).

In the meantime, you can use an older version ([v1.3.14](https://github.com/unchase/Unchase.OpenAPI.Connectedservice/releases/tag/v1.3.14)) of the Connected Service, where there is no bug.
