### ISSUE TITLE
I cannot generate code from file with size 528kb

### ISSUE THREAD

**Issue by sinanaltaii** [unchase/Unchase.OpenAPI.Connectedservice#15]
I trying to generate client code for open api json file with size 528kb and it does not work, but, when i try with another file with size 115kb, that file works. Is it possible to fix this?

**Comment by unchase** [comment]
Hi, @sinanaltaii 
Can you send me json-file to spiritkola@hotmail.com (directly from email)?

**Comment by unchase** [comment]
@sinanaltaii Is the issue still relevant?

**Comment by sinanaltaii** [comment]
I actually solved it with a workaround that I don't remember :)

// Sinan
________________________________

**Comment by unchase** [comment]
If you remember the workaround, please share in this issue.
Thank you.
