### ISSUE TITLE
VS 2019 OpenAPI code generator same as Unchase?

### ISSUE THREAD

**Issue by vindberg** [unchase/Unchase.OpenAPI.Connectedservice#16]
Hi, im using the latest version of VS 2019 and have added a swagger service reference in Connected Services.

Im trying to get the generated httpclient to include a custom type (converted from string (example: BigInteger)). How can this be done using Unchase and is it the same way when using VS Connected Services directly?

Hope you can help.

**Comment by unchase** [comment]
Hi, @vindberg 
Can you provide more data or some code?

**Comment by unchase** [comment]
You should create [the same issue](https://github.com/RicoSuter/NSwag/issues) in NSwag repository, because of the Connected Service use [NSwag.Commands](https://www.nuget.org/packages/NSwag.Commands/) inside.

**Comment by vindberg** [comment]
Thanks
