### ISSUE TITLE
Unable to read string as a response

### ISSUE THREAD

**Issue by Z33shan4li** [unchase/Unchase.OpenAPI.Connectedservice#17]
Hi, 
I am unable to read the string response, as it always tries to deserialize the response. is there any way to read the string, int without deserialization?

**Comment by unchase** [comment]
Can you provide more data?

**Comment by Z33shan4li** [comment]
`public async System.Threading.Tasks.Task<Group> ApiV1GroupsGetgroupsbyinstitutionAsync(string institutionNumber, System.Threading.CancellationToken cancellationToken)
        {
            var urlBuilder_ = new System.Text.StringBuilder();
            urlBuilder_.Append(BaseUrl != null ? BaseUrl.TrimEnd('/') : "").Append("/api/v1/Groups/GetGroupsByInstitution?");
            if (institutionNumber != null) 
            {
                urlBuilder_.Append(System.Uri.EscapeDataString("institutionNumber") + "=").Append(System.Uri.EscapeDataString(ConvertToString(institutionNumber, System.Globalization.CultureInfo.InvariantCulture))).Append("&");
            }
            urlBuilder_.Length--;
    
            var client_ = new System.Net.Http.HttpClient();
            try
            {
                using (var request_ = new System.Net.Http.HttpRequestMessage())
                {
                    request_.Method = new System.Net.Http.HttpMethod("GET");
                    request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("text/plain"));
    
                    PrepareRequest(client_, request_, urlBuilder_);
                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);
                    PrepareRequest(client_, request_, url_);
    
                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    try
                    {
                        var headers_ = System.Linq.Enumerable.ToDictionary(response_.Headers, h_ => h_.Key, h_ => h_.Value);
                        if (response_.Content != null && response_.Content.Headers != null)
                        {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }
    
                        ProcessResponse(client_, response_);
    
                        var status_ = ((int)response_.StatusCode).ToString();
                        if (status_ == "200") 
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<Group>(response_, headers_).ConfigureAwait(false);
                            return objectResponse_.Object;
                        }
                        else
                        if (status_ == "404") 
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<string>(response_, headers_).ConfigureAwait(false);
                            throw new ApiException<string>("Not Found", (int)response_.StatusCode, objectResponse_.Text, headers_, objectResponse_.Object, null);
                        }
                        else
                        if (status_ == "400") 
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<string>(response_, headers_).ConfigureAwait(false);
                            throw new ApiException<string>("Bad Request", (int)response_.StatusCode, objectResponse_.Text, headers_, objectResponse_.Object, null);
                        }
                        else
                        if (status_ != "200" && status_ != "204")
                        {
                            var responseData_ = response_.Content == null ? null : await response_.Content.ReadAsStringAsync().ConfigureAwait(false); 
                            throw new ApiException("The HTTP status code of the response was not expected (" + (int)response_.StatusCode + ").", (int)response_.StatusCode, responseData_, headers_, null);
                        }
            
                        return default(Group);
                    }
                    finally
                    {
                        if (response_ != null)
                            response_.Dispose();
                    }
                }
            }
            finally
            {
                if (client_ != null)
                    client_.Dispose();
            }
        }`


This is a code generated by the extension but it throws exception at 

`var objectResponse_ = await ReadObjectResponseAsync<string>(response_, headers_).ConfigureAwait(false);`

because the response is a simple string and code is unable to deserialize it

**Comment by unchase** [comment]
Hi, @Z33shan4li 

```csharp
try
{ 
    //...
    var group = await ApiV1GroupsGetgroupsbyinstitutionAsync(number);
}
catch (ApiException<string> ex)
{
    //if (ex.StatusCode != 200) // you can check statusCode
    var stringResult = ex.Result;
}
```
