### ISSUE TITLE
Question: Is there a way to re-generate from ConnectedService.json

### ISSUE THREAD

**Issue by dloukola** [unchase/Unchase.OpenAPI.Connectedservice#19]
Hi,

This service is great! 

I however, don't understand what the `ConnectedService.json` is supposed to do if there is no way to re-generate the classes from it?
I can modify `MyClient.nswag` and open it in nswag studio, and that works, but what is the `ConnectedService.json` for then?

My gut feeling is that I'm just missing something and I can't seem to find a setting/button for this.

Dave

**Comment by johanpellkvist** [comment]
I think something happend here. In previous versions it was possible to change URL, but now grayed out when trying to update.

**Comment by unchase** [comment]
> I think something happend here. In previous versions it was possible to change URL, but now grayed out when trying to update.

@johanpellkvist Updating the connected service should not imply changing the url (by design).
Which cases might require changing the url when updating?

**Comment by unchase** [comment]
I can return this opportunity, but is it right?

**Comment by drwatson85** [comment]
@unchase This item does not show up in my context menu in the solution explorer.
Any idea why that could be?

![image](https://user-images.githubusercontent.com/11414707/99070792-36936300-25b1-11eb-8067-a523e22a70af.png)

**Comment by unchase** [comment]
Hi, @drwatson85

Can you try to regenerate the code again with the connected service?
Probably, this issue (you can not update the code) appeared after update of the connected service.
