### ISSUE TITLE
Cannot use parent class in client

### ISSUE THREAD

**Issue by Kshopper93** [unchase/Unchase.OpenAPI.Connectedservice#21]
Hi,

i have two classes both with the same parent class
```

CLASSES
public class MailMessageSmtpData : MailData
{
     public int SmtpPort { get; set; }
}

public class MailMessageSendGridData : MailData
{
     public int ApiKey{ get; set; }
}

public class MailData
{
     public string Subject { get; set; }
}

CONTROLLER

[HttpPost]
[Route("mail/smtp")]
[ProducesResponseType(typeof(MailMessage), 200)]
public async Task<IActionResult> SendSmtpMail([FromBody] MailMessageSmtpData m)
{
     return Ok(await new MailMessageService().SendMailWithSmtp(m));
}

[HttpPost]
[Route("mail/sendgrid")]
[ProducesResponseType(typeof(MailMessage), 200)]
public async Task<IActionResult> SendSendGridMail([FromBody]  MailMessageSendGridData m)
{
     return Ok(await new MailMessageService().SendMailWithSendGrid(m));
}



CLIENT CODE

-> MailData Class did not exist
 private MailData data= new MailData(); 

```

My problem here is that i can't instantiate an object from type MailData in my client code.
Can't find the MailData class in the generated code.

How can i solve this issue?

**Comment by unchase** [comment]
Hi, @Kshopper93 
What error does the IDE swoh you?
Can you attach the screenshot?

**Comment by Kshopper93** [comment]
https://i.imgur.com/u0Mf8a2.png

**Comment by Kshopper93** [comment]
Hello,

do you found any issue in my code?

**Comment by unchase** [comment]
Hi, @Kshopper93 

Please, attach a screenshot of the generated `MailData` class.
Or send me the specification file by which the code was generated (to spiritkola@hotmail.com directly).

**Comment by Kshopper93** [comment]
Hi, 

there is no MailData class in the generated file.  I habe only the Child classes MailMessageSmtPData and MailMessageSendGridData.
The MailData (Parent class) variables merged into the child chlasses. But i need the Base and Child classes separately

![image](https://user-images.githubusercontent.com/7681603/80344172-6eca9280-8867-11ea-917d-4be73c4ff0a3.png)



Where can i find the  specification file?

**Comment by unchase** [comment]
You can find this file in the directory with the generated client (it has the extension - json):

![spec](https://user-images.githubusercontent.com/29679226/80346911-33829080-8874-11ea-989d-2735f2a7e096.png)

**Comment by Kshopper93** [comment]
@unchase - U got a Email with the File.

Thank you

**Comment by unchase** [comment]
@Kshopper93 
There is no `MailMessage` contract in json-specification file (there is only `MailMessageSmtpData` and `MailMessageSendGridData`), therefore, it is not created in client code.

Should to look the issue on the server side, which generates the specification, because the connected service generates a client based on the specification passed to it.

**Comment by Kshopper93** [comment]
@unchase 
Can I send you the full Project and you can take a look?

**Comment by unchase** [comment]
Of course, send, I will try to help.

**Comment by Kshopper93** [comment]
@unchase 

U got a email with github link to my project.

Thank you.

**Comment by unchase** [comment]
@Kshopper93 
See [the same issue](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1146). There is a problem in specification generation: generates without base classes.
it's not implemented yet in [Swashbuckle.AspNetCore](https://github.com/domaindrivendev/Swashbuckle.AspNetCore).

You can try to use [NSwag](https://github.com/RicoSuter/NSwag) in the server side for generating specification. It seems to be allows to generate base classes in the specification schema: see [this](https://github.com/RicoSuter/NJsonSchema/wiki/Inheritance) and [this](https://github.com/RicoSuter/NJsonSchema/issues/5) topics.
