### ISSUE TITLE
Need options with "name" and replacing node name

### ISSUE THREAD

**Issue by zlanizer** [unchase/Unchase.OpenAPI.Connectedservice#24]
Using this part

```
        "review" : {
          "type" : "array",
          "xml" : {
            "name" : "reviews",
            "wrapped" : true
          },
          "items" : {
            "$ref" : "#/definitions/BlaBla"
          }
        }
```
will generate field with name **review** and attribute
```
[Newtonsoft.Json.JsonProperty("**review**" ,...)]
public System.Collections.Generic.IEnumerable review{ get; set; }
```
It will be nice that if another options will exists like 

- using **name**  value for attribute name
- using **name**  value for property name
- using **name**  value for attribute and property name

```
[Newtonsoft.Json.JsonProperty("**reviews**" ,...)]
public System.Collections.Generic.IEnumerable review{ get; set; }
```

**Comment by unchase** [comment]
Hi, @zlanizer 
Since the Сonnected service uses [NSwag Commands](https://www.nuget.org/packages/NSwag.Commands/) for code generation, you should create the same issue in [this repository](https://github.com/RicoSuter/NSwag/issues).
