### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by gthelp** [unchase/Unchase.OpenAPI.Connectedservice#25]
When using Autowrapper (https://github.com/proudmonkey/AutoWrapper) on service, the json comes back with additional fields that do not show in swagger json that wraps the response object.

So when the connected service builds, it builds for the response object but not the wrapper put on by Autowrapper. Has anyone experienced this or found a quick workaround? I am trying not to modify the generated class.

thanks,
Greg

**Comment by unchase** [comment]
Hi, @gthelp 
This feature is not supported by the Connected Service.
