### ISSUE TITLE
Error: Cannot populate JSON array onto ype 'NJsonSchema.JsonSchemaProperty'

### ISSUE THREAD

**Issue by weitzhandler** [unchase/Unchase.OpenAPI.Connectedservice#29]
### Describe the bug
When trying to populate [this](https://github.com/amzn/selling-partner-api-models/blob/main/models/fba-inventory-api-model/fbaInventory.json) spec, I get the following error:

>Error: Cannot populate JSON array onto ype 'NJsonSchema.JsonSchemaProperty'. Path 'definitions.Granularity.properties.enum', line 35, position 17..

And the client doesn't generate.

### Assemblies affected

*Which assemblies and versions are known to be affected?*

### Steps to reproduce

*The simplest set of steps to reproduce the issue. If possible, reference a commit that demonstrates the issue:*

1. Create a new VS project
2. Try adding a connected service of the attached file
3. See error

### Expected result

Clients generated

### Actual result

Error

### Screenshots

![image](https://user-images.githubusercontent.com/2716316/93463362-529bc080-f8f0-11ea-9a90-06ef25a1ab62.png)

**Comment by unchase** [comment]
I checked [this specification](https://github.com/amzn/selling-partner-api-models/blob/main/models/fba-inventory-api-model/fbaInventory.json) in [editor.swagger.io](https://editor.swagger.io/):

![image](https://user-images.githubusercontent.com/29679226/93466338-c2ac4580-f8f4-11ea-800c-320e653a217d.png)

Need to fix the specification before client generation.

**Comment by weitzhandler** [comment]
I'm so sorry I'm new to Swagger and OAS and didn't know about editor.swagger.io.
Will report the error to that vendor, thank you for this, and thanks for your great and helpful tools!
