### ISSUE TITLE
The configuration wizard should not require a .json extension

### ISSUE THREAD

**Issue by Tjeerd-menno** [unchase/Unchase.OpenAPI.Connectedservice#3]
There's a good number of swagger endpoints online which expose the swagger doc using an endpoint which does not have .json extension in the URL. 

Currently it's impossible to generate code for such documents.

**Comment by unchase** [comment]
Hello. Do you mean yaml-files? Could you give an example of such a public endpoint?

**Comment by Tjeerd-menno** [comment]
Hi. Not YAML it's Swagger JSON. But without and extension.

e.g. https://api.bol.com/retailer/public/apispec/v3

**Comment by unchase** [comment]
Thanks for the feedback. Fix this issue in the next update.
