### ISSUE TITLE
Error caused when generating C# code from OpenApi json file (Bungie.net API) 

### ISSUE THREAD

**Issue by iJacks1980** [unchase/Unchase.OpenAPI.Connectedservice#34]
Software versions:

- Unchase 1.5.10
- Visual Studio 2019 Pro 16.8.3

When using the OpenApi specification json file available from: https://github.com/Bungie-net/api/blob/master/openapi.json

And using the following options:

![image](https://user-images.githubusercontent.com/76005029/102798508-238e6280-43a9-11eb-94e8-776984b6a2cb.png)

Unchase generator produces the following output:

> Adding service instance for "D:\Downloads\openapi.json"...
> Adding Nuget Packages for OpenAPI (Swagger) CSharp Client...
> Nuget Package "Newtonsoft.Json" for OpenAPI (Swagger) already installed.
> Nuget Package "System.Net.Http" for OpenAPI (Swagger) already installed.
> Nuget Package "System.ComponentModel.Annotations" for OpenAPI (Swagger) already installed.
> Nuget Packages for OpenAPI (Swagger) CSharp Client were installed.
> Generating NSwag-file for OpenAPI (Swagger)...
> NSwag-file "OpenAPI.nswag" for OpenAPI (Swagger) was generated.
> Generating Client Proxy for OpenAPI (Swagger) Client...
> Warning:Error: Error converting value True to type 'System.Collections.Generic.ICollection`1[System.String]'. Path 'components.headers.X-API-Key.required', line 41425, position 24..
> Client Proxy for OpenAPI (Swagger) Client was generated.
> Adding service instance complete!

No client code is generated.

I am uncertain if this is caused by an invalid OpenAPI json file, if this is something that I am doing wrong, or if this is an odd edge case.  Source OpenAPI json is attached.

[openapi.zip](https://github.com/unchase/Unchase.OpenAPI.Connectedservice/files/5725352/openapi.zip)

If there is any additional information that I can provide which will be helpful please let me know.

**Comment by unchase** [comment]
The issue occurs during code generation, duplicate the issue in [this repo](https://github.com/RicoSuter/NSwag/issues) to solve it (the Connected service code generation is based on NSwag).

Workaround: just comment the line in the openapi specification:

```json
"headers": {
  "X-API-Key": {
	"description": "When you have registered an Application at https://www.bungie.net/en/Application, you will receive an API key.  You should pass it in via this header with every request.",
	// "required": false,
	"allowEmptyValue": false,
	"schema": {
	  "type": "string"
	}
  }
},
```
