### ISSUE TITLE
Error: Exception has been thrown by the target of an invocation..

### ISSUE THREAD

**Issue by metju30** [unchase/Unchase.OpenAPI.Connectedservice#35]
When generating C# client with option: **Generate contracts output**

Re-adding service instance for "C:\tmp\c#\WebAPI\zzi.si-e-customs-1.0.0-resolved.json"...
Generating NSwag-file for OpenAPI (Swagger)...
NSwag-file "eCustomsAPI.nswag" for OpenAPI (Swagger) was generated.
Generating Client Proxy for OpenAPI (Swagger) Client...
**Warning:Error: Exception has been thrown by the target of an invocation..**
Client Proxy for OpenAPI (Swagger) **Client was generated**.
Re-Adding service instance complete!

Client is NOT generated .. what is wrong?

[zzi.si-e-customs-1.0.0-resolved.txt](https://github.com/unchase/Unchase.OpenAPI.Connectedservice/files/5762037/zzi.si-e-customs-1.0.0-resolved.txt)

**Comment by metju30** [comment]
.. when leaving out that option it generates client. After adding System.Runtime.Serialization.dll ..
There are still compilation errors: **" ... not all code paths return a value ..."**

![image](https://user-images.githubusercontent.com/11869489/103486576-23f21900-4dff-11eb-90bb-b6910efb221c.png)

Perhaps should be something like this:
![image](https://user-images.githubusercontent.com/11869489/103486652-a11d8e00-4dff-11eb-8329-8401f380a228.png)

**Comment by unchase** [comment]
Hi, @metju30 
Since the Connected service uses [NSwag Commands](https://www.nuget.org/packages/NSwag.Commands/) for code generation, you should create the same issue in [this repository](https://github.com/RicoSuter/NSwag/issues).
