### ISSUE TITLE
BUG : Unable to inject baseUrl in constructor   

### ISSUE THREAD

**Issue by muhammadaqibbp** [unchase/Unchase.OpenAPI.Connectedservice#36]
### Describe the bug
I am unable to inject baseUrl in constructor while generating client from application in .net framework 4.6.1 using **Swashbuckle v.5.6.0**.

I have selected the all the option related to baseUrl but it can not work

![BaseUrl](https://user-images.githubusercontent.com/25838218/104914309-c3dba500-59b0-11eb-8e22-2c7bd2f12fc6.PNG)

but It generated the following  code

![CrmCode](https://user-images.githubusercontent.com/25838218/104914583-2cc31d00-59b1-11eb-86a4-6581b6bce562.PNG)

### Assemblies affected

*Which assemblies and versions are known to be affected?*

### Steps to reproduce

*The simplest set of steps to reproduce the issue. If possible, reference a commit that demonstrates the issue:*

...

### Expected result

*What would happen if there wasn't a bug.*

### Actual result

*What is actually happening.*

### Additional detail

*Optional, details of the root cause if known.*

**Comment by unchase** [comment]
Hi, @muhammadaqibbp 
You can set the base URL with `BaseUrl` property in the `CRMClient` class after creating or can add your own constructor (with setting base URL) for this **partial** class in other place.

**Comment by muhammadaqibbp** [comment]
Hi,
I have done in this way but after the updating client it will remove that property form constructor. Any way around to preserve our changes on client update
