### ISSUE TITLE
Feature: C# Client dialog reads in properties from previously generated Client.nswag

### ISSUE THREAD

**Issue by mikhey** [unchase/Unchase.OpenAPI.Connectedservice#37]
When updating a client, every setting, option, selection has to be documented in order to reproduce the OpenAPI client consistently.  It would be a nice feature to _not_ have to remember/document these settings but instead use (or ask to use) a previously generated nswag file generated by this connected service.

**Comment by unchase** [comment]
Hi, @mikhey 
Unfortunately, not all options can be saved to a nswag-file, so the settings are saved separately.
In addition, we need to save the same (last) settings for different services so as not to set them up again.

**Comment by mikhey** [comment]
I wonder if that could be done by using the URL (and potentially API version) as a key in a JSON settings file possibly?  Given that would most likely be the unique key between generated clients.  

Eventually, I plan to use the .nswag configs for NuGet package creation/automation in DevOps so that clients can be generated as the API is updated.  

Also, I just wanted to say that this has been a tremendous springboard for us to generate clients using VS tooling!  Keep it up!!

**Comment by unchase** [comment]
All settings are documented in the `ConnectedService.json` file when the client code is generated.
The .nswag file has a specific structure (used by NSwagStudio), so I cannot modify it (add new fields to it).
Perhaps `ConnectedService.json` is suitable for your purposes?

**Comment by mikhey** [comment]
`ConnectedService.json` sounds like a place for it.

**Comment by unchase** [comment]
Nice. Try to use it to suit your needs. Share your experience if possible. Or ideas for how to improve the experience with the connected service.
