### ISSUE TITLE
<Not edit Unchase OpenAPI (Swagger) Connected Service>

### ISSUE THREAD

**Issue by eriellensouza** [unchase/Unchase.OpenAPI.Connectedservice#41]
The Connected Services component 'Unchase OpenAPI (Swagger) Connected Service' failed: (HRESULT:0x80131500) Error setting value to 'PathPrefix' on 'Microsoft.OpenApi.OData.OpenApiConvertSettings'.

**Comment by unchase** [comment]
Hi, @eriellensouza 
Could you please show your `ConnectedService.json`?

**Comment by eriellensouza** [comment]
{
  "ProviderId": "Unchase.OpenAPI.ConnectedService",
  "Version": "1.5.6.0",
  "GettingStartedDocument": {
    "Uri": "https://github.com/unchase/Unchase.OpenAPI.Connectedservice/"
  },
  "ExtendedData": {
    "ServiceName": "AuthADWS",
    "GeneratedFileName": "AuthADWS",
    "Endpoint": "http://authad-qa.adiq.io/swagger/v1/swagger.json",
    "GeneratedFileNamePrefix": null,
    "GenerateCSharpClient": true,
    "GenerateTypeScriptClient": false,
    "GenerateCSharpController": false,
    "OpenApiToCSharpClientCommand": {
      "ClientBaseClass": null,
      "ConfigurationClass": null,
      "GenerateClientClasses": true,
      "GenerateClientInterfaces": true,
      "ClientBaseInterface": null,
      "InjectHttpClient": true,
      "DisposeHttpClient": true,
      "ProtectedMethods": [],
      "GenerateExceptionClasses": true,
      "ExceptionClass": "ApiException",
      "WrapDtoExceptions": true,
      "UseHttpClientCreationMethod": false,
      "HttpClientType": "System.Net.Http.HttpClient",
      "UseHttpRequestMessageCreationMethod": false,
      "UseBaseUrl": true,
      "GenerateBaseUrlProperty": true,
      "GenerateSyncMethods": false,
      "ExposeJsonSerializerSettings": false,
      "ClientClassAccessModifier": "public",
      "TypeAccessModifier": "public",
      "GenerateContractsOutput": false,
      "ContractsNamespace": null,
      "ContractsOutputFilePath": null,
      "ParameterDateTimeFormat": "s",
      "ParameterDateFormat": "yyyy-MM-dd",
      "GenerateUpdateJsonSerializerSettingsMethod": true,
      "UseRequestAndResponseSerializationSettings": false,
      "SerializeTypeInformation": false,
      "QueryNullValue": "",
      "ClassName": "AuthADWS",
      "OperationGenerationMode": 5,
      "AdditionalNamespaceUsages": [],
      "AdditionalContractNamespaceUsages": [],
      "GenerateOptionalParameters": false,
      "GenerateJsonMethods": false,
      "EnforceFlagEnums": false,
      "ParameterArrayType": "System.Collections.Generic.IEnumerable",
      "ParameterDictionaryType": "System.Collections.Generic.IDictionary",
      "ResponseArrayType": "System.Collections.Generic.ICollection",
      "ResponseDictionaryType": "System.Collections.Generic.IDictionary",
      "WrapResponses": false,
      "WrapResponseMethods": [],
      "GenerateResponseClasses": true,
      "ResponseClass": "SwaggerResponse",
      "Namespace": "Adiq.Backoffice.Antecipacao.Integracao.AuthADWS",
      "RequiredPropertiesMustBeDefined": true,
      "DateType": "System.DateTimeOffset",
      "JsonConverters": null,
      "AnyType": "object",
      "DateTimeType": "System.DateTimeOffset",
      "TimeType": "System.TimeSpan",
      "TimeSpanType": "System.TimeSpan",
      "ArrayType": "System.Collections.Generic.ICollection",
      "ArrayInstanceType": "System.Collections.ObjectModel.Collection",
      "DictionaryType": "System.Collections.Generic.IDictionary",
      "DictionaryInstanceType": "System.Collections.Generic.Dictionary",
      "ArrayBaseType": "System.Collections.ObjectModel.Collection",
      "DictionaryBaseType": "System.Collections.Generic.Dictionary",
      "ClassStyle": 0,
      "GenerateDefaultValues": true,
      "GenerateDataAnnotations": true,
      "ExcludedTypeNames": [],
      "ExcludedParameterNames": [],
      "HandleReferences": false,
      "GenerateImmutableArrayProperties": false,
      "GenerateImmutableDictionaryProperties": false,
      "JsonSerializerSettingsTransformationMethod": null,
      "InlineNamedArrays": false,
      "InlineNamedDictionaries": false,
      "InlineNamedTuples": true,
      "InlineNamedAny": false,
      "GenerateDtoTypes": true,
      "GenerateOptionalPropertiesAsNullable": false,
      "GenerateNullableReferenceTypes": false,
      "TemplateDirectory": null,
      "TypeNameGeneratorType": null,
      "PropertyNameGeneratorType": null,
      "EnumNameGeneratorType": null,
      "ServiceHost": null,
      "ServiceSchemes": null,
      "output": "AuthADWS.cs",
      "newLineBehavior": 0
    },
    "ExcludeTypeNamesLater": false,
    "OpenApiToTypeScriptClientCommand": null,
    "OpenApiToCSharpControllerCommand": null,
    "Variables": null,
    "Runtime": 0,
    "CopySpecification": false,
    "OpenGeneratedFilesOnComplete": false,
    "UseRelativePath": false,
    "ConvertFromOdata": false,
    "OpenApiConvertSettings": {
      "ServiceRoot": "http://localhost",
      "Version": {
        "Major": 1,
        "Minor": 0,
        "Build": 1,
        "Revision": -1,
        "MajorRevision": -1,
        "MinorRevision": -1
      },
      "EnableKeyAsSegment": null,
      "EnableUnqualifiedCall": false,
      "EnableOperationPath": true,
      "EnableOperationImportPath": true,
      "EnableNavigationPropertyPath": true,
      "TagDepth": 4,
      "PrefixEntityTypeNameBeforeKey": false,
      "OpenApiSpecVersion": 1,
      "EnableOperationId": true,
      "EnableUriEscapeFunctionCall": false,
      "VerifyEdmModel": false,
      "IEEE754Compatible": false,
      "TopExample": 50,
      "EnablePagination": false,
      "PageableOperationName": "listMore",
      "EnableDiscriminatorValue": false,
      "EnableDerivedTypesReferencesForResponses": false,
      "EnableDerivedTypesReferencesForRequestBody": false,
      "PathPrefix": "",
      "ShowLinks": false,
      "ShowSchemaExamples": false
    },
    "OpenApiSpecVersion": 1,
    "UseNetworkCredentials": false,
    "NetworkCredentialsUserName": null,
    "NetworkCredentialsPassword": null,
    "NetworkCredentialsDomain": null,
    "WebProxyUri": null,
    "UseWebProxy": false,
    "UseWebProxyCredentials": false,
    "WebProxyNetworkCredentialsUserName": null,
    "WebProxyNetworkCredentialsPassword": null,
    "WebProxyNetworkCredentialsDomain": null
  }
}

**Comment by unchase** [comment]
Change `"PathPrefix": "",` to `"PathPrefix": "Odata",` and try again.

**Comment by eriellensouza** [comment]
Is there any reason why the PathPrefix field is ""? It was some update of the extension?

**Comment by unchase** [comment]
Did you generate the client code with the lastest version of the connected service first time?

**Comment by eriellensouza** [comment]
The error occurs with the old versions already generated from the client.

**Comment by eriellensouza** [comment]
The one generated with the recent version does not occur this registered error.
