### ISSUE TITLE
Split generated classes and interfaces into dedicated files

### ISSUE THREAD

**Issue by nobba75** [unchase/Unchase.OpenAPI.Connectedservice#45]
Hi, 
first of all nice work!

Is it possible to split the generated file (now containing all interfaces/classes) into separate files? That is, Each class into one file and each interface into one file?

**Comment by unchase** [comment]
Hi, @nobba75 

The Connected Service based on [NSwag](https://github.com/RicoSuter/NSwag):
See https://github.com/RicoSuter/NSwag/issues/1398
