### ISSUE TITLE
Updating / Regenerating a service client causes error in Visual Studio

### ISSUE THREAD

**Issue by bharatpidapa** [unchase/Unchase.OpenAPI.Connectedservice#46]
<img width="434" alt="UpdateFailure" src="https://user-images.githubusercontent.com/40465091/112152510-bf05be00-8bb8-11eb-8e32-851f4045dcb1.PNG">
If you try to update a previously added connected service (OpenAPI C# client) an error happens and Visual Studio shows a message box. The connected service is also not updated.

The error message is:

Connected Services

The Connected Services component 'Unchase OpenAPI
(Swagger) Connected Service' failed: (HRESULT:0x80131500)
Error setting value to 'PathPrefix' on
'Microsoft.OpenApi.OData.OpenApiConvertSettings'.

**Comment by unchase** [comment]
Hi, @bharatpidapa 

See: https://github.com/unchase/Unchase.OpenAPI.Connectedservice/issues/38

**Comment by bharatpidapa** [comment]
Updating the "PathPrefix": "" to  "PathPrefix": "Odata" resoved the issue. 


Thank you.
