### ISSUE TITLE
Incorrect generated method names

### ISSUE THREAD

**Issue by seruss** [unchase/Unchase.OpenAPI.Connectedservice#47]
Generated method names contain endpoint name and request type e.g. PostersGetAsync, while client generated with built-in tool creates names according to description (parameter operationId) e.g. GeneratePosterRequestAsync

**Comment by unchase** [comment]
Hi, @seruss 
You can change this option:

![image](https://user-images.githubusercontent.com/29679226/114091248-1a29f700-98c1-11eb-8ca0-a9569f071294.png)
