### ISSUE TITLE
Case Sensitive file system prevents detection of configured specification endpoints

### ISSUE THREAD

**Issue by Garonenur** [unchase/Unchase.OpenAPI.Connectedservice#48]
I have two versions of the same repository on my PC - one is set up within a folder that has case sensitivity activated and was created by git in WSL2.
The other was cloned within a folder with **de**activated case sensitivity (the windows default) using git for windows in a powershell.

Within the windows variety, I can right click on a previously configured specification endpoint and I get the context-menu entry `Update Unchase OpenApi…`.
In the other one this menu point never appears and I can only create new endpoints. Double clicking `Connected Services` shows a green check mark and the word `Configured`, for the case insensitive version, but nothing if the file system is case sensitive.

As .Net 5 moves to be compatible with other operating systems and development for .Net is not windows exclusive any more, it would be cool if this tool could handle file names in a case sensitive way.

**Comment by unchase** [comment]
Hi, @Garonenur 
Can you show me some screenshots or animated gifs with this issue?

**Comment by DiWiWeinmannEmt** [comment]
hi, same person here, but now with a company-account.

ok. so screenshots from the case sensitive folder
![caseSensitiveContextMenu](https://user-images.githubusercontent.com/82499768/114674772-dd6a5f80-9d07-11eb-8602-bf5c92a3767a.png)
![caseSensitiveConnectedServiceView](https://user-images.githubusercontent.com/82499768/114674803-e52a0400-9d07-11eb-86e2-e6a414b1f66d.png)

and a clone of the same repository, but created case **IN**sensitive (which is windows default)
![caseINsensitiveContextMenu](https://user-images.githubusercontent.com/82499768/114674822-e9eeb800-9d07-11eb-8ad8-91f41acb5cb0.png)
![caseINsensitiveConnectedServiceView](https://user-images.githubusercontent.com/82499768/114674837-ee1ad580-9d07-11eb-88e8-8143329221a5.png)

would this help? I have to be careful what I screenshot here.

In the Connected Services view/menu I can click on the `Other Services` -> `Unchase OpenAPI …` entry and it will create a new endpoint in the solution explorer, but it will not recognize it afterwards like it does without case sensitivity.

**Comment by unchase** [comment]
Hi, @DiWiWeinmannEmt

I assume that this issue will not be resolved within the specific connected service. This is the work of Visual Studio itself and its mechanism for interacting with connected services.

I would recommend that you address this issue [here](https://github.com/microsoft/ConnectedServices).

**Comment by unchase** [comment]
Perhaps [this article](https://devblogs.microsoft.com/commandline/per-directory-case-sensitivity-and-wsl/) will help.
