### ISSUE TITLE
BUG generated code fails with runtime error

### ISSUE THREAD

**Issue by johnpfmg** [unchase/Unchase.OpenAPI.Connectedservice#51]
### Describe the bug
the generated code at line 1493 var dictionary_ = in attached file fails with error below
 var json_ = Newtonsoft.Json.JsonConvert.SerializeObject(parameterValues, _settings.Value);
 var dictionary_ = Newtonsoft.Json.JsonConvert.DeserializeObject<System.Collections.Generic.Dictionary<string, string>>(json_, _settings.Value);

  
### Assemblies affected

*Which assemblies and versions are known to be affected?*

### Steps to reproduce

using .net core 3.1
add the attached class UnchaseIssueDemo.cs.txt to a console app or other host app.
Run the code

...

### Expected result

expect generated code to work
### Actual result
*What is actually happening.*
[UnchaseIssueDemo.cs.txt](https://github.com/unchase/Unchase.OpenAPI.Connectedservice/files/6399813/UnchaseIssueDemo.cs.txt)
[ContentAccessAPIClient.cs.txt](https://github.com/unchase/Unchase.OpenAPI.Connectedservice/files/6399816/ContentAccessAPIClient.cs.txt)

get error 
Message=Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'System.Collections.Generic.Dictionary`2[System.String,System.String]' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
[ContentAccessAPIClient.cs.txt](https://github.com/unchase/Unchase.OpenAPI.Connectedservice/files/6399654/ContentAccessAPIClient.cs.txt)

### Additional detail

*Optional, details of the root cause if known.*

**Comment by unchase** [comment]
Hi, @johnpfmg 

See RicoSuter/NSwag#3414

**Comment by johnpfmg** [comment]
From your reply I see other are having this issue,  is there a planed date to have this issue fixed?

jcp

**Comment by unchase** [comment]
This issue occurs on the side of the NSwag.Commands library that the Connected service depends on.
Therefore, the timing of the fix depends on the maintainer of the NSwag project.
