### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by AZDeveloper777** [unchase/Unchase.OpenAPI.Connectedservice#52]
Visual Studio 2019 16.9.4

Using the OpenAPI file  https://github.com/bigcommerce/api-specs/blob/master/reference/catalog.v3.yml
with Unchase to generate a C# client creates methods with bad parameters.

i.e. 
CatalogProductsGetAsync(id, id:in, id:not_in, id:min, id:max, id:greater, id:less, etc....

**Comment by unchase** [comment]
This is due to the c # variable naming convention. For example, such a name is not valid (`:` is present):

![image](https://user-images.githubusercontent.com/29679226/117531915-95c8b200-afed-11eb-92b9-4ca68ef20450.png)
