### ISSUE TITLE
Error trying to update the connected service

### ISSUE THREAD

**Issue by Krimsar** [unchase/Unchase.OpenAPI.Connectedservice#55]
When trying to execute `Update Unchase OpenAPI (Swagger) Connected Service...` on a connected service, which was generated with an older version, I get the following error: 
![grafik](https://user-images.githubusercontent.com/3831785/121554859-cba8ee00-ca12-11eb-8585-6ce7814b5bf8.png)

When I set the `OpenApiConvertSettings->PathPrefix` to "OData" in `ConnectedService.json` and save the file, the above command works and the Wizard displays correctly.

My Version: 1.5.26

**Comment by unchase** [comment]
Hi, @Krimsar 

The same issues are: https://github.com/unchase/Unchase.OpenAPI.Connectedservice/issues/46, https://github.com/unchase/Unchase.OpenAPI.Connectedservice/issues/38, https://github.com/unchase/Unchase.OpenAPI.Connectedservice/issues/41

**Comment by Krimsar** [comment]
Oh sorry, I didn't look for closed tickets. The problem still persists in the newest version though. You wrote on another issure, that we need to regenerate not update? What do you mean by that exactly? Because I am not aware of another method where I don#t lose my configuration other than using `Update Unchase OpenAPI (Swagger) Connected Service...`

**Comment by unchase** [comment]
Just delete generated code and create it again with adding the connected service.

**Comment by Krimsar** [comment]
This is what I meant by losing my configuration. In this case everything I adjusted and changed from the default is lost, isn't it? That is very user-unfriendly.

**Comment by unchase** [comment]
This only applies to navigating between specific versions of the connected service. In the future, this issue will not occur.

**Comment by Krimsar** [comment]
I am well aware of that, I'm just not quite sure why this issue cannot be fixed without user intervention. No worries though, there is a workaround...

**Comment by stefanluchian** [comment]
@Krimsar , would you be so kind to describe your workaround? I also struggle with that problem of upgrading and would be very helpful.

**Comment by Krimsar** [comment]
@stefanluchian Sure, like I mentioned in the report, when I set the `OpenApiConvertSettings->PathPrefix` to "OData" in the file ConnectedService.json (should be able to be found in the project files) and save the file it works.

**Comment by stefanluchian** [comment]
Oh, thanks. It works.
But then, the file gets populated with a bunch of new properties. Hopefully these are the default values and correspond to the old behaviour.
