### ISSUE TITLE
Visual Studio 2022 Support

### ISSUE THREAD

**Issue by kfrancis** [unchase/Unchase.OpenAPI.Connectedservice#56]
### Installed product versions
Visual Studio: 2022 All Versions

### Description
Make the extension available in Visual Studio 2022.

### Steps to recreate
1. Download the extension installer.
2. Run the installer.

### Current behaviour
The message that it is already installed to all applicable products appears even though it is not installed in Visual Studio 2022.
It is also not listed in Online Extensions in Manage Extensions Visual Studio 2022.

### Expected behaviour
Installs and works in Visual Studio 2022.

Note: Sorry for all the extra details. I probably could have stopped with the title on this one.

**Comment by kfrancis** [comment]
Working on this here: https://github.com/kfrancis/Unchase.OpenAPI.Connectedservice

**Comment by unchase** [comment]
Hi, @kfrancis 

Apparently you already have experience with migration to Visual Studio 2022. You can help me with the migration using PR.

**Comment by kfrancis** [comment]
I was more or less just following Mads on his stream: https://www.youtube.com/watch?v=-PKIPTW6km0&list=PLReL099Y5nRdG2n1PrY_tbCsUznoYvqkS

**Comment by vip32** [comment]
MS just released some ['extension update' documentation](https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022) for VS2022, maybe that helps.

Having no experience developing VS extensions: but isn't adding VS2022 support just modifying the manifest file?
![image](https://user-images.githubusercontent.com/164303/138049520-6bbc03ad-9a9d-448c-b9df-15e16b5b72bc.png)

**Comment by Corey-J** [comment]
What's the current status of this upgrade following the additional information?
Is help still required?

**Comment by unchase** [comment]
Hi, @Corey-J 
Unfortunately, I don't have enough free time right now to devote it to this issue. Any help is greatly appreciated.

**Comment by kfrancis** [comment]
Sorry everyone, I don't personally know how to do this. I did try to, but it's a bit beyond my capabilities. The code for extensions are a bit magic.

**Comment by unchase** [comment]
Hi all.
I'll try to find time next weekend.

**Comment by unchase** [comment]
Unfortunately, I don't have enough time right now to do this. But I will port the extension to VS2022 a few later.

**Comment by Corey-J** [comment]
> Unfortunately, I don't have enough time right now to do this. But I will port the extension to VS2022 a few later.

Hey, I was wondering if there was any opportunities for sponsoring this migration through my workplace. We heavily rely on this plugin and its currently the last thing we need to migrate to .NET 6 and VS2022. 

Thanks

**Comment by unchase** [comment]
Hi, @Corey-J
I cannot migrate some projects to .NET6 too until I update the extension. So, I think I will deal with it in the near future)

**Comment by SoundarRBT** [comment]
As a workaround, I'm directly using [NSwag Studio](https://github.com/RicoSuter/NSwag/wiki/NSwagStudio) to open the `.nswag` file generated in the connected service. We just need to update the open api specification in nswag studio & click 'Generate Outputs' & 'Generate Files' to update the C# client code. It's pretty much the same experience as 'Unchase.OpenAPI.Connectedservice' except that we need to run this out of VS 2022.

Hope this helps someone until this extension is released for VS2022

**Comment by unchase** [comment]
> MS just released some ['extension update' documentation](https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022) for VS2022, maybe that helps.
> 
> Having no experience developing VS extensions: but isn't adding VS2022 support just modifying the manifest file? ![image](https://user-images.githubusercontent.com/164303/138049520-6bbc03ad-9a9d-448c-b9df-15e16b5b72bc.png)

Unfortunately, things are a little more complicated for Connected Services.
Also, there is no VS2022 migration instruction for it.

**Comment by unchase** [comment]
@kfrancis @vip32 @Corey-J @SoundarRBT Done in [v1.7.0](https://github.com/unchase/Unchase.OpenAPI.Connectedservice/releases/tag/v1.7.0)
Could you test it please?

**Comment by Corey-J** [comment]
@unchase 

Thanks for getting this updated, everything appears to be mostly functional.

The only oddity is that connected services are showing in their own folder instead of the 'Actual' connected services. Was this intended?

**Comment by unchase** [comment]
> @unchase
> 
> Thanks for getting this updated, everything appears to be mostly functional.
> 
> The only oddity is that connected services are showing in their own folder instead of the 'Actual' connected services. Was this intended?

No, the main code hasn't changed. Probably an issue with the new SDK
