### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by tellybrown** [unchase/Unchase.OpenAPI.Connectedservice#6]
Seems the Connected Service is dependent upon a nuget package that doesnt exist anymore.

`Adding service instance for "https://raw.githubusercontent.com/unbound-tech/ukc_rest/master/admin.yaml"...
Adding Nuget Packages for OpenAPI (Swagger) CSharp Client...
Nuget Package "Newtonsoft.Json" for OpenAPI (Swagger) already installed.
Nuget Package "System.Net.Http" for OpenAPI (Swagger) already installed.
Nuget Package "System.ComponentModel.Annotations" for OpenAPI (Swagger) already installed.
Nuget Packages for OpenAPI (Swagger) CSharp Client were installed.
Generating NSwag-file for OpenAPI (Swagger)...
Warning:NSwag-file for OpenAPI (Swagger) was not generated. Error: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040).
Generating Client Proxy for OpenAPI (Swagger) Client...
Warning:Client Proxy for OpenAPI (Swagger) Client was not generated. Error: Object reference not set to an instance of an object..
Adding service instance complete!
Error:Adding Unchase OpenAPI (Swagger) Connected Service to the project failed: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
`

**Comment by CarlAimProductions** [comment]
I'm getting this problem.. It needs Newtonsoft Json version 12.0.0.0 which does not exist

**Comment by unchase** [comment]
@CarlAimProductions сould you provide a screenshot and the metadata file.

**Comment by CarlAimProductions** [comment]
![unchase](https://user-images.githubusercontent.com/25052798/70607546-ef615d00-1bfe-11ea-8da7-2b468475f159.PNG)

**Comment by CarlAimProductions** [comment]
[csproj.pdf](https://github.com/unchase/Unchase.OpenAPI.Connectedservice/files/3949461/csproj.pdf)

**Comment by unchase** [comment]
Fix this issue in [297cdf7](https://github.com/unchase/Unchase.OpenAPI.Connectedservice/commit/297cdf73116f9aab5e2bac3327822f61473aee72) commit - [v1.3.14](https://github.com/unchase/Unchase.OpenAPI.Connectedservice/releases/tag/v1.3.14).
