### ISSUE TITLE
Set explicitly values to AllowNull

### ISSUE THREAD

**Issue by JacekWalczak92** [unchase/Unchase.OpenAPI.Connectedservice#60]
Right now, some of the objects from the response body are set with the value DisallowNull, however, they can be null, I think this happens because all optional values are by default transform to Required = [..].Disallownull -> is there any way to change this behaviour via UI before generating a service script for certain values or for all such stuff?

**Comment by C1yde** [comment]
![image](https://user-images.githubusercontent.com/15062514/172162197-3277844b-82b6-4781-a4ea-7286d7128188.png)

Try to call this extension method in your **_ConfigureServices_** for correct swagger generation.

![image](https://user-images.githubusercontent.com/15062514/172162439-867fea20-e361-4b90-9b98-33b6342c404c.png)
