### ISSUE TITLE
about DateFormatConverter   questions

### ISSUE THREAD

**Issue by oreo1024** [unchase/Unchase.OpenAPI.Connectedservice#63]
DateFormatConverter  default value "yyyy-MM-dd" ,I  hope format"yyyy-MM-dd HH:mm:ss", how to config?

**Comment by unchase** [comment]
Hi, @oreo1024 
You can change it there:

![image](https://user-images.githubusercontent.com/29679226/140746723-ba4086a6-1cf2-4773-bd6f-a4cb549c9977.png)

**Comment by oreo1024** [comment]
![Dingtalk_20211109082954](https://user-images.githubusercontent.com/24849005/140840016-03a1b6a2-65b8-4a7c-875a-6bbc62239498.jpg)
this  is my setting

**Comment by oreo1024** [comment]
![Dingtalk_20211109083022](https://user-images.githubusercontent.com/24849005/140840104-4493fbcf-697a-4993-889b-bf8d7947bfd8.jpg)
this is generate core ,Not the result I want

**Comment by oreo1024** [comment]
@unchase
