### ISSUE TITLE
HOW-TO: Configure the tool to regenerate output files on change of the input specification file/url? 

### ISSUE THREAD

**Issue by glyad** [unchase/Unchase.OpenAPI.Connectedservice#67]
We are lack an option to regenerate generated files on spec changes automatically.

**Comment by unchase** [comment]
Hi, @glyad 
Unfortunately, now there is no such possibility. Perhaps in the future I will add it, but not soon.

**Comment by Kammoz** [comment]
I would like to 1up this! 👍
