### ISSUE TITLE
no code generated

### ISSUE THREAD

**Issue by gitback2work** [unchase/Unchase.OpenAPI.Connectedservice#7]
It appears that there is an error with a path variable or something but no suggestion what to do. I only used default settings. Here is the output. What should I do?

Adding Nuget Packages for OpenAPI (Swagger) CSharp Client...
Nuget Package "Newtonsoft.Json" for OpenAPI (Swagger) already installed.
Nuget Package "System.Net.Http" for OpenAPI (Swagger) already installed.
Nuget Package "System.ComponentModel.Annotations" for OpenAPI (Swagger) already installed.
Nuget Packages for OpenAPI (Swagger) CSharp Client were installed.
Generating NSwag-file for OpenAPI (Swagger)...
NSwag-file "ArtistApiService.nswag" for OpenAPI (Swagger) was generated.
Generating Client Proxy for OpenAPI (Swagger) Client...
Warning:Error: Unexpected character encountered while parsing value: <. Path '', line 0, position 0..
Client Proxy for OpenAPI (Swagger) Client was generated.
Adding service instance complete!

**Comment by maurosampietro** [comment]
Got the exact same problem. Any way to workaround this?

**Comment by unchase** [comment]
Hi, @maurosampietro 

Could you give an example of the specification for which you are generating the client?

**Comment by Banner-Keith** [comment]
For anyone else that runs into this in the future try hitting the json url from a browser in a new private window, or from a shell script so you can see if you're actually getting the json file, or if you are hitting some kind of html page like a log in or error page.
