### ISSUE TITLE
BUG Visual Studio 17.2.0 Update removes context menu

### ISSUE THREAD

**Issue by joedirt** [unchase/Unchase.OpenAPI.Connectedservice#70]
### Describe the bug
After upgrading Visual Studio 2022 to 17.2.0, the right-click context menu on "Connected Services" no longer shows the option to update the existing Swagger/OpenAPI configuration.

### Assemblies affected

Visual Studio Unchase Extension

### Steps to reproduce

1. Update Visual Studio 2022 to 17.2.0
2. Open solution and project containing a previously configured OpenAPI connected service.
3. Right click on "Connect Services"
4. Context Menu option is missing.  No errors

### Expected result

Right click context menu should display an option to update the configured service

### Actual result

Context Menu option is missing

### Screenshots

Visual Studio 2022 17.2.0 (missing context menu option)

![image](https://user-images.githubusercontent.com/190430/168848765-e07679e1-8c0c-4f18-a311-0eac3455b0b1.png)

Visual Studio 2019 16.11.11 (context menu option visible)
![image](https://user-images.githubusercontent.com/190430/168848647-e64b479b-97af-4398-ab40-30007659b7ac.png)

**Comment by CaffeineDaemon** [comment]
We have the same issue with Visual Studio 17.3.0 Preview 1.0.

**Comment by raabesebastian** [comment]
Same issue with Visual Studio 17.2.1

**Comment by Elyspio** [comment]
We have the same issue with Visual Studio 17.2.0 Preview 6.0.

**Comment by solayuta** [comment]
Same issue with Visual Studio 17.2.2

**Comment by kulenski** [comment]
Same here with 17.2.2 Community.

Is there any workaround to execute "update definition" through command prompt or package management console?

**Comment by solayuta** [comment]
1.uninstall visual studio
2.Install 17.1.7 version
https://docs.microsoft.com/zh-cn/visualstudio/releases/2022/release-history

**Comment by lachezar-gizdov** [comment]
Same here for VS 17.2.2

@kulenski you can use the nswag desktop client to update the definition.

**Comment by Sayan751** [comment]
Only workaround that worked for me is to use the prompt to add the connected service, and use the same service name and file name while providing the URI for swagger.json. It updated my existing client.

**Comment by joedirt** [comment]
What I have had to do is use UnChase to create the initial dependency, then go outside Visual Studio and into NSwagStudio, select the generated .nswag file and click "Generate Files" in order to refresh/update the proxy class.

Not an ideal process to say the least.  How can I help bump this bug up in importance?

**Comment by MarkGodwin** [comment]
It's still broken in 17.2.3. But it's not an issue with this plugin - all connected service plugins are affected.
I confirmed it works fine with 17.1

**Comment by MarkGodwin** [comment]
Looks like there has been some movement on the Developer Community issue.
It's now shown as "Fixed - Pending Release"!

**Comment by Nicopika** [comment]
By installing the latest release 17.3, the problem was fixed.

**Comment by jon49** [comment]
I'm having this issue for 17.3.x and 17.4. It shows the `Update Unchase OpenAPI (Swagger) Connectected Service...` but when I right click on the `Connected Services` it doesn't show the option to create a new one. I'm also on Windows 11 but not sure if that is related.
