### ISSUE TITLE
Generation of client code from YAML wont compile in NET 4.8 / 6 class library 

### ISSUE THREAD

**Issue by southernskip** [unchase/Unchase.OpenAPI.Connectedservice#74]
Trying to create a service for Canada customs described here. 
https://ccp-pcc.cbsa-asfc.cloud-nuage.canada.ca/en/carm-api/tariff-codes

I click a create a new connected service for my .NET Framework 4.8 project (also test fresh .NET 6 class library) in Visual Studio 2022

Select: Unchase Open API(Swagger) Connected Service

I set the Service Name field to CARMService
I check Generate CSharp Client
I set the specification endpoint to:   
https://ccp-pcc.cbsa-asfc.cloud-nuage.canada.ca/en/assets/carm-api/tariff_codes/en_api.yaml
Click Finish (no further settings selected) 

The code will not compile due to tonnes of errors

Illegal method naming: 

 public System.Threading.Tasks.Task<string> TariffClassifications$countAsync(AcceptLanguage2 accept_Language, string search, string filter)

Strange method formatting:

    public System.Threading.Tasks.Task<TariffClassificationsType> TariffClassifications(TariffNumber='',AsOfDate=)Async(AcceptLanguage3 accept_Language, string tariffNumber, string asOfDate, System.Collections.Generic.IEnumerable<Anonymous4> select, System.Collections.Generic.IEnumerable<Anonymous5> expand)

**Comment by unchase** [comment]
Hi, @southernskip

The Connected Service based on [NSwag](https://github.com/RicoSuter/NSwag).

Should create the same issue in [this place](https://github.com/RicoSuter/NSwag/issues).
