### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by michaels23** [unchase/Unchase.OpenAPI.Connectedservice#79]
Does Unchase OpenAPI work with the Visual Studio community edition?

I've installed it, but I don't see "Add Connected Service" when I right-click on my Connected Services folder.
![image](https://user-images.githubusercontent.com/618047/209233678-55ee35b6-eed9-4c9c-8b67-7d97dbe4a3b8.png)

**Comment by unchase** [comment]
Hi, @michaels23 
You should use "Add" -> "Connected Service"

![image](https://user-images.githubusercontent.com/29679226/209325925-b4c3e514-e93a-434b-9993-3805bff77107.png)

![image](https://user-images.githubusercontent.com/29679226/209325952-dd3ca699-600c-47fa-8608-76c7a505ec3c.png)

**Comment by michaels23** [comment]
Thanks!
