### ISSUE TITLE
BUG: Data Annotations in DTO generated even if option is unticked

### ISSUE THREAD

**Issue by temelj** [unchase/Unchase.OpenAPI.Connectedservice#8]
### Describe the bug
The tooling seems to ignore the option **Generate data annotation attributes.**

### Assemblies affected

CSharp Client Settings - c# DTO generation

### Steps to reproduce

Use tooling to create DTOs only (without client)
...

### Expected result
Expected Code Snipped of the Generated.cs
```
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.27.0 (Newtonsoft.Json v12.0.0.2)")]
    public partial class ACHPmtBasicType 
    {
        public string AchpmtId { get; set; }
    
```

### Actual result

```
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.27.0 (Newtonsoft.Json v12.0.0.2)")]
    public partial class ACHPmtBasicType 
    {
        [Newtonsoft.Json.JsonProperty("achpmtId", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string AchpmtId { get; set; }
    
```

**Comment by unchase** [comment]
Did you uncheck "Required properties must be defined in JSON" option in "DTO classes" - "Serialization" block?

**Comment by temelj** [comment]
Hi,
I'm sorry for the delayed response. We tried using this at work and I really liked the options menu (rather than command line).  I will try this tomorrow and get back to you.

**Comment by temelj** [comment]
Hey,
I just re-generated the DTOs unchecking **"Required properties must be defined in JSON"** and **"Generate data annotation attributes."** and its still generating the annotations.

**Comment by unchase** [comment]
Hi, @temelj 
You should [create the same issue](https://github.com/RicoSuter/NSwag/issues) in NSwag repository, because of the Connected Service use [NSwag.Commands](https://www.nuget.org/packages/NSwag.Commands/) inside.
This issue can be resolved with a library fix.
