### ISSUE TITLE
Unable to Set DataAnnotations ErrorMessage For Dto

### ISSUE THREAD

**Issue by nitinag217** [unchase/Unchase.OpenAPI.Connectedservice#82]
When trying to create Service, Unable to Set DataAnnotations ErrorMessage For Dto, Please check below images: In Image2 for EmailAddress Property did not set Error Message.

![Image1](https://user-images.githubusercontent.com/30688445/220575080-8684c439-0001-4ec7-95e4-5ec615bbab68.PNG)
![Image2](https://user-images.githubusercontent.com/30688445/220575084-d00b3358-d8d3-45df-9750-9046e344eeef.PNG)

**Comment by unchase** [comment]
Hi, @nitinag217 
The Connected Service based on [NSwag](https://github.com/RicoSuter/NSwag).


Should create the same issue in [this place](https://github.com/RicoSuter/NSwag/issues).
