### ISSUE TITLE
Feature Request: Allow Relative Path for swagger.json file

### ISSUE THREAD

**Issue by temelj** [unchase/Unchase.OpenAPI.Connectedservice#9]
Basically, the tooling currently supports a URI or a file.
The URI is great in most cases, however in our use-case, the URI cannot be reached (due to network restrictions / proxy).

Therefore a file based approach works, however a full relative path is used instead of a relative path to the project (such that the swagger.json can be checked in and updated as required in the future but linked form the source repository rather than a full file path)

Hopefully I was clear enough in my explanation. Thank you

**Comment by temelj** [comment]
Cheers :)

I would have flagged it as a feature but I think bug was by default.

**Comment by unchase** [comment]
Could you describe use-case in more detail with examples?

**Comment by temelj** [comment]
oh crap, i apologise for missing this comment.

The usecase woudl be to check-in a swagger file as embedded resource so that you can have a copy of the file in source control that is used to generate the POCOs.

I know, it serves no purpose for the code base itself but it does allow to keep a history on the changes on the source and then your tool can be used to re-generate the objects based on the latest checked in swagger.json.

**Comment by unchase** [comment]
This has been added to Connected Service in [b3008e4](https://github.com/unchase/Unchase.OpenAPI.Connectedservice/commit/b3008e4025a437fd9d975b60e1c80e30ccb68d14) commit.
